name: Build paper images

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        paper:
          - mc_version: 1.16.5
            paper_version: 692
      fail-fast: true
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: nicoenking/papermc:${{ matrix.paper.mc_version }}
          build-args: |
            MC_VERSION=${{ matrix.paper.mc_version }}
            PAPER_VERSION=${{ matrix.paper.paper_version }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}